In [32]:
import numpy as np

In [46]:
array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])

In [47]:
array1[0]

0

In [48]:
array1[2]

2

In [49]:
array1[-1]

15

In [50]:
array1[-2]

14

In [51]:
array1[[1, 3, 4]] # 1번, 3번, 4번 인덱스만 가져옴

array([1, 3, 4])

In [52]:
array2 = np.array([2, 1, 3])

In [53]:
# array1을 array2로 인덱싱
array1[array2] # 2번, 1번 3번 인덱스만 가져옴

array([2, 1, 3])

In [54]:
array1[2:7] # 2번, 7 (7-1)번 인덱스 전까지 가져옴

array([2, 3, 4, 5, 6])

In [55]:
array1[0:7] # 0부터 7(7-1)번 인덱스 전까지 가져옴

array([0, 1, 2, 3, 4, 5, 6])

In [56]:
array1[:7] # 0부터 7 (7-1)번 인덱스까지

array([0, 1, 2, 3, 4, 5, 6])

In [57]:
array1[2:] 

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [58]:
array1[2:11:2]

array([ 2,  4,  6,  8, 10])

In [60]:
array1[2:11:3]

array([2, 5, 8])