In [1]:
import numpy as np

In [3]:
array1 = np.array([2, 3, 5, 7, 11, 13, 17 ,19 , 23, 29, 31])

In [4]:
array1 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [5]:
array1 % 2 == 0

array([ True, False, False, False, False, False, False, False, False,
       False, False])

In [6]:
booleans = np.array([True, True, False, True, False, True])

In [7]:
np.where(booleans)

(array([0, 1, 3, 5]),)

In [8]:
array1 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [10]:
np.where(array1 > 4) # 4보다 큰 값이 있는 인덱스만 가져옴

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),)

In [11]:
# filter를 이용해 인덱싱을 할 수있다.
filter = np.where(array1 > 4)
filter

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),)

In [12]:
array1[filter] # 4보다 큰 값들만 인덱싱

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])